version: '3.4'

services:
  webapp:
    image: y95535/webapp:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webapp$
    volumes:
      - C:\Users\jiede\source\repos\restfulapi\webapp:/app
      - C:\Users\jiede\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_webapp$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webapp$ bin/Debug/netcoreapp2.1/webapp.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
